# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ceviriProgrami23.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 100, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 30, 551, 491))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_cevir = QtWidgets.QPushButton(self.groupBox)
        self.btn_cevir.setGeometry(QtCore.QRect(190, 210, 93, 28))
        self.btn_cevir.setObjectName("btn_cevir")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 161, 31))
        self.label_2.setObjectName("label_2")
        self.txt_metin = QtWidgets.QLineEdit(self.groupBox)
        self.txt_metin.setGeometry(QtCore.QRect(0, 80, 201, 101))
        self.txt_metin.setObjectName("txt_metin")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.label_3.setObjectName("label_3")
        self.btn_ko = QtWidgets.QRadioButton(self.groupBox)
        self.btn_ko.setGeometry(QtCore.QRect(10, 200, 131, 20))
        self.btn_ko.setObjectName("btn_ko")
        self.btn_uz = QtWidgets.QRadioButton(self.groupBox)
        self.btn_uz.setGeometry(QtCore.QRect(10, 230, 131, 20))
        self.btn_uz.setObjectName("btn_uz")
        self.btn_ja = QtWidgets.QRadioButton(self.groupBox)
        self.btn_ja.setGeometry(QtCore.QRect(10, 260, 131, 20))
        self.btn_ja.setObjectName("btn_ja")
        self.txt_ceviri = QtWidgets.QLineEdit(self.groupBox)
        self.txt_ceviri.setGeometry(QtCore.QRect(280, 80, 201, 101))
        self.txt_ceviri.setObjectName("txt_ceviri")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(280, 50, 101, 31))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_cevir.setText(_translate("MainWindow", "Çevir"))
        self.label_2.setText(_translate("MainWindow", "       ÇEVİRİ PROGRAMI"))
        self.label_3.setText(_translate("MainWindow", "METİN"))
        self.btn_ko.setText(_translate("MainWindow", "KORECE"))
        self.btn_uz.setText(_translate("MainWindow", "ÖZBEKÇE"))
        self.btn_ja.setText(_translate("MainWindow", "JAPONCA"))
        self.label_4.setText(_translate("MainWindow", "ÇEVİRİ METNİ"))
